import Head from 'next/head';
import { Inter } from 'next/font/google';
import { BsLinkedin } from "react-icons/bs";
import { BsGithub } from "react-icons/bs";
import { MdEmail } from "react-icons/md";
import { BsFillMoonStarsFill } from "react-icons/bs";
import ProjectList from './projects';
import { useState } from 'react';
import AnimatedOnScroll from './animateOnScroll';

import { AiFillHtml5 } from "react-icons/ai";
import { DiCss3 } from "react-icons/di";
import { DiJavascript } from "react-icons/di";
import { SiJquery } from "react-icons/si";
import { FaReact } from "react-icons/fa";
import { SiNextdotjs } from "react-icons/si";
import { GrGraphQl } from "react-icons/gr";
import { FaNodeJs } from "react-icons/fa";
import { SiMongodb } from "react-icons/si";
import { SiMysql } from "react-icons/si";
import { SiBootstrap } from "react-icons/si";
import { SiTailwindcss } from "react-icons/si";





const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  let gitIconColor = "#171A22"
  let moonIconColor = "#202837"
  let emailIconColor = "#202837"

  if (darkMode) {
    gitIconColor = "#F1F6FC"
    moonIconColor = "#E3E7F0"
    emailIconColor = "#E3E7F0"
  }

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kevin Heaton</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Antic+Didone&family=GFS+Didot&family=Source+Sans+Pro&display=swap" rel="stylesheet"></link>
      </Head>
      <main className="">
        <div className="min-h-full min-w-full flex flex-wrap bg-cover bg-slate-200 dark:bg-gray-800">

          <div className="flex flex-wrap min-w-full">
            <BsFillMoonStarsFill size={36} color={moonIconColor} className="absolute top-11 left-5" onClick={() => setDarkMode(!darkMode)}/>
            <button className="absolute top-5 right-5 rounded-lg bg-gray-800 hover:bg-gray-900 dark:bg-slate-200 dark:hover:bg-slate-300">
              <a href='/files/KevinHeatonResume.pdf' 
                alt='Resume of Kevin Heaton' 
                target='_blank' 
                rel='noopener noreferrer' 
                locale={true}
                className="p-2 justify-center align-middle text-white dark:text-gray-800" >
                  Resume
                </a>
            </button>
          </div>

          <div className="min-w-full min-h-screen flex flex-wrap flex-col justify-center align-middle">
            <h1 className=" justify-center align-middle min-w-full flex flex-wrap text-center text-[#1D2135] dark:text-[#F7F7F8] text-6xl sm:text-9xl">
              Kevin Heaton
            </h1>

            <p className="justify-center align-middle flex max-w-full text-center text-3xl sm:text-4xl p-5">
              Software developer employing a background in education to create more user friendly experiences.
            </p>

            <ul className="flex flex-wrap justify-center">
              <a href="https://www.linkedin.com/in/kevin-heaton-663b2ab5/" target="_blank">
                <li className="m-3">
                  <BsLinkedin size={56} color="#0277b5" />
                </li>
              </a>

              <a href="https://github.com/KevinHeaton" target="_blank">
                <li className="m-3">
                  <BsGithub size={56} color={gitIconColor}/>
                </li>
              </a>

              <a href="mailto:williamkevinheaton@gmail.com" target="_blank">
                <li>
                 <MdEmail size={65} color={emailIconColor} className="m-2" /> 
                </li>
              </a>
            </ul>
          </div>

          <AnimatedOnScroll>
          <div className="min-w-full min-h-fit">
            
            <h2 className="align-middle justify-center min-w-full flex flex-wrap text-5xl text-[#1D2135] dark:text-[#F7F7F8] sm:text-7xl p-5 focus:animate-bounce">
              About Me
            </h2>
          

            <p className="justify-center align-middle flex max-w-full text-left text-xl sm:text-2xl p-5">
              Coding was never something that I imagined myself doing. I had preconceived notions regarding what it meant to be a developer and it felt somewhat out of reach for someone with my experience. However, once I let go of those ideas and gave it a shot I was instantly hooked. I loved being able to create something from scratch and seeing the endless possibilities that programming holds. The more I learned the more I realized you can never know it all and that further fueled my passion. I consider myself a lifelong learner and doing something where you can never stop growing excites me.
              <br />
              <br />
              My previous work experience has allowed me to wear many hats and hone many skills. I have been able to work well under pressure and balance multiple priorities in a constantly evolving environment. Through my time in The Coding Boot Camp at UT Austin I have gained experience as a full stack developer, with in-depth knowledge of JavaScript and other widely used languages and a strong understanding of what it means to work in this field. Throughout my time as a teacher and in The Coding Boot Camp, I have also had the opportunity to work with a diverse group of individuals who come from all backgrounds and I pride myself on always maintaining positive and genuine relationships with my colleagues and superiors.
            </p>

            <h2 className="align-middle justify-center min-w-full flex flex-wrap text-5xl text-[#1D2135] dark:text-[#F7F7F8] sm:text-7xl p-5">
              My Mission
            </h2>

            <p className="justify-center align-middle flex max-w-full text-left text-xl sm:text-2xl p-5">
              Software Developer employing a background in teaching to find creative solutions to coding challenges with skills in JavaScript, React,
              SQL, and more. Always looking for solutions as a relentless problem solver and consistently looking for the best responsive designs. Excels
              working in teams where communication is a top priority. Excited to learn new stacks and share learning with others. As a part of a highquality team, created a web application that allows people in Austin to post and RSVP to events. Excited to be a part of a fast paced and
              driven team to ensure the world continues to run smoothly. Best traits are analyzing complex problems, communication, self-directed, and
              teamwork.
            </p>
          </div>
          </AnimatedOnScroll>

          <AnimatedOnScroll>
          <div className="min-w-full min-h-fit sm:min-h-screen xl:min-h-fit mt-32">
            <h2 className="align-middle justify-center min-w-full flex flex-wrap text-5xl text-[#1D2135] dark:text-[#F7F7F8] sm:text-7xl p-5">
              Portfolio
            </h2>

            <p className="justify-center flex max-w-full text-left text-xl sm:text-2xl p-5 min-w-full">
              Since starting my coding journey, I've created a wide range of apps and websites. My GitHub profile has all of my projects, but below are some of my favorites!
            </p>

            <ProjectList />
          </div>
          </AnimatedOnScroll>

          <AnimatedOnScroll>
          <div className="min-w-full  min-h-fit flex flex-wrap justify-center align-middle my-32">
            <h2 className="align-middle justify-center min-w-full flex flex-wrap text-5xl text-[#1D2135] dark:text-[#F7F7F8] sm:text-7xl p-5">
              My Stack
            </h2>

            <div className="m-5 flex flex-wrap">
              <a href="https://developer.mozilla.org/en-US/docs/Glossary/HTML5" className="m-1" target="_blank">
                <AiFillHtml5 size={56} color="#e34f26" />
              </a>
              <a href="https://developer.mozilla.org/en-US/docs/Web/CSS" className="m-1" target="_blank">
                <DiCss3 size={56} color="#264de4" />
              </a>
              <a href="https://www.javascript.com/" className="m-1" target="_blank">
                <DiJavascript size={56} color="#f0db4f" />
              </a>
              <a href="https://reactjs.org/" className="m-1" target="_blank">
                <FaReact size={56} color="#61dafb" />
              </a>
              <a href="https://nextjs.org/" className="m-1" target="_blank">
                <SiNextdotjs size={56} color="#000000" />
              </a>
              <a href="https://nodejs.org/en/" className="m-1" target="_blank">
                <FaNodeJs size={56} color="#339933" />
              </a>
              <a href="https://jquery.com/" className="m-1" target="_blank">
                <SiJquery size={56} color="#0769ad" />
              </a>
              <a href="https://www.mongodb.com/" target="_blank">
                <SiMongodb size={56} color="#47a248" />
              </a>
              <a href="https://www.mysql.com/" className="m-1" target="_blank">
                <SiMysql size={56} color="#4479a1" />
              </a>
              <a href="https://graphql.org/" className="m-1" target="_blank">
                <GrGraphQl size={56} color="#e535ab" />
              </a>
              <a href="https://getbootstrap.com/" className="m-1" target="_blank">
                <SiBootstrap size={56} color="#563d7c" />
              </a>
              <a href="https://tailwindcss.com/" className="m-1" target="_blank">
                <SiTailwindcss size={56} color="#06b6d4" />
              </a>
            </div>
          </div>
          </AnimatedOnScroll>

          <AnimatedOnScroll>
          <div className="flex flex-wrap justify-center min-w-full my-10">
            <h2 className="align-middle min-w-full justify-center flex flex-wrap text-5xl text-[#1D2135] dark:text-[#F7F7F8] sm:text-7xl px-5">
              Contact Me
            </h2>

            <p className="flex max-w-full text-left text-xl sm:text-2xl p-5">
              Want to get in touch? Feel free to contact me by email at williamkevinheaton@gmail.com or through LinkedIn!
            </p>
          </div>
          </AnimatedOnScroll>

        </div>
      </main>
    </div>
  )
}
